Feature/share modal
kis-sprint/zero-one-zero-web pull request #26
Opened 2023-09-10 11:19 UTC by chaeyun-sim

#### 공유하기 모달을 만들었습니다.

input 부분이나 '코드 복사' 버튼을 누르면 코드가 바로 복사되고,
'바로 공유하기'를 누르면 자체 공유하기로 넘어갑니다.

<img width="397" alt="스크린샷 2023-09-10 오후 8 17 45" src="https://github.com/kis-sprint/zero-one-zero-web/assets/111689342/1759b2ab-d7e7-47d7-b636-e42eea78997c">

2023-09-10 11:55 UTC, choegyumin requested changes, later dismissed
다른 코드 보고 맞춰주세요 👍 

- 컴포넌트 함수 선언문
- props 타입 이름, export 추가
- 이벤트 핸들러 네이밍

2023-09-10 11:55 UTC, choegyumin commented on src/components/ShareModal.tsx
> +                    />
여기서 sliceText 함수 실행하지말고 위에서 반환값을 변수로 뽑아두는게 좋겠어요
scope를 더럽히지 않고 싶었던 거라면 즉시 실행 함수(IIFE)로 작성하시면 돼요

2023-09-10 11:55 UTC, choegyumin commented on src/components/ShareModal.tsx
> +};
조금 더 명확한 이름을 사용하는게 좋아 보여요

2023-09-10 12:10 UTC, chaeyun-sim commented on src/components/ShareModal.tsx
> +                    />
> 여기서 sliceText 함수 실행하지말고 위에서 반환값을 변수로 뽑아두는게 좋겠어요
> scope를 더럽히지 않고 싶었던 거라면 즉시 실행 함수(IIFE)로 작성하시면 돼요

변수로 뽑아두는게 뭘까요...?

2023-09-10 12:22 UTC, chaeyun-sim commented on src/components/ShareModal.tsx
> +                    />
useEffect로 모달이 열리자마자 길이 확인하고 자르도록 만들어뒀습니다!

2023-09-10 13:59 UTC, choegyumin commented on src/components/ShareModal.tsx
> +                    />
> 변수로 뽑아두는게 뭘까요...?

`value={sliceText()}` 말고 `value={slicedText}` 처럼 쓸 수 있도록 값 선언해두란 뜻이었어요.
근데 이제 그럴 필요 없어졌네요 👍

2023-09-10 14:02 UTC, choegyumin commented on src/components/ShareModal.tsx
> +};
`ShareModalProps` 라고 짓는게 좋아보여요

2023-09-11 08:23 UTC, choegyumin approved these changes

2023-09-11 08:26 UTC, merged